openapi: 3.0.0
info:
  title: SGS - Sistema de Gerenciamento de Salas
  version: "1.0"
paths:
  /salas/:
    get:
      summary: Listar todas as salas
      responses:
        '200':
          description: Uma lista de salas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    capacidade:
                      type: integer
                    disponivel:
                      type: boolean
  /salas/{id}/reservar:
    post:
      summary: Reservar uma sala
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID da sala a ser reservada
      responses:
        '200':
          description: Reserva efetuada com sucesso
        '404':
          description: Sala não encontrada ou indisponível